#!/usr/bin/bash
set -euo pipefail

# Section 1: Expected table (exact numeric values reproduced from the analysis)
cat > /workspace/expected.md <<'EOTABLE'
**Table 9: RQ2: Ordinal logistic regression results of the relationship between perceived understandability of the functional constructs and (i) participants’ usage frequency, and (ii) constructs’ complexity (except for MRF)**

**Lambda (90 data points)**

| Term        |   OR | Estimate | StdError | t-value | p-value |
| ----------- | ---: | -------: | -------: | ------: | ------: |
| Usage Freq. | 2.29 |     0.83 |     0.31 |    2.65 |    0.02 |
| Compl.      | 0.88 |    -0.13 |     0.18 |   -0.73 |    0.47 |

**Comprehension (120 data points)**

| Term        |   OR | Estimate | StdError | t-value | p-value |
| ----------- | ---: | -------: | -------: | ------: | ------: |
| Usage Freq. | 1.49 |     0.40 |     0.22 |    1.84 |    0.07 |
| Compl.      | 0.77 |    -0.26 |     0.11 |   -2.27 |    0.05 |

**MRF (103 data points)**

| Term        |   OR | Estimate | StdError | t-value | p-value |
| ----------- | ---: | -------: | -------: | ------: | ------: |
| Usage Freq. | 1.79 |     0.58 |     0.25 |    2.31 |    0.02 |
EOTABLE

# Section 2: Ensure artifact is present
artisan get https://zenodo.org/records/10554377 >/dev/null 2>&1 || true

# Section 3: Run the published analysis inside the provided Docker image
cd ICSE2024-funcConstructs-Artifacts/ICSE2024-funcConstructs-Artifacts

docker pull mdipenta/rexp:latest >/dev/null
docker run -d --init --entrypoint bash --name rexp_repro -v"${PWD}":/data --workdir /data mdipenta/rexp:latest -c 'sleep infinity'
docker exec rexp_repro /bin/bash --noprofile --norc -c "R --no-save < FuncConstructs-Statistics.r"

# Section 4: Programmatically build repro.txt from produced CSVs (so outputs come from computation)
REPRO=/workspace/repro.txt
echo "**Table 9: RQ2: Ordinal logistic regression results of the relationship between perceived understandability of the functional constructs and (i) participants’ usage frequency, and (ii) constructs’ complexity (except for MRF)**" > "$REPRO"
echo "" >> "$REPRO"

format_csv_row() {
  # args: csvfile, row_number (1-based; header is row 1)
  f="$1"; r="$2"
  if [ ! -f "$f" ]; then
    echo "| ?.?? | ?.?? | ?.?? | ?.?? | ?.?? |" 
    return
  fi
  line=$(sed -n "$((r))p" "$f" || true)
  # remove quotes and whitespace
  line=$(echo "$line" | tr -d '"' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  # If empty, return placeholders
  if [ -z "$line" ]; then
    echo "| ?.?? | ?.?? | ?.?? | ?.?? | ?.?? |"
    return
  fi
  # CSV columns: OR,Value,Std. Error,t value,p value  (as generated by the R script)
  IFS=',' read -r OR EST SE TV PV <<< "$line"
  # format numeric fields to two decimals (if numeric), else leave as-is
  format_num() {
    v="$1"
    if echo "$v" | grep -Eq '^-?[0-9]+([.][0-9]+)?$'; then
      printf "%.2f" "$v"
    else
      printf "%s" "$v"
    fi
  }
  printf "| %s | %s | %s | %s | %s |\n" "$(format_num "$OR")" "$(format_num "$EST")" "$(format_num "$SE")" "$(format_num "$TV")" "$(format_num "$PV")"
}

# Lambda
echo "**Lambda (90 data points)**" >> "$REPRO"
echo "" >> "$REPRO"
echo "| Term        |   OR | Estimate | StdError | t-value | p-value |" >> "$REPRO"
echo "| ----------- | ---: | -------: | -------: | ------: | ------: |" >> "$REPRO"
lambda_csv="results/Table-9-rq2-lambda.csv"
# header is row 1, coefficients at rows 2 and 3
row1=$(format_csv_row "$lambda_csv" 2)
row2=$(format_csv_row "$lambda_csv" 3)
echo "| Usage Freq. $row1" >> "$REPRO"
echo "| Compl.      $row2" >> "$REPRO"
echo "" >> "$REPRO"

# Comprehension
echo "**Comprehension (120 data points)**" >> "$REPRO"
echo "" >> "$REPRO"
echo "| Term        |   OR | Estimate | StdError | t-value | p-value |" >> "$REPRO"
echo "| ----------- | ---: | -------: | -------: | ------: | ------: |" >> "$REPRO"
comp_csv="results/Table-9-rq2-comp.csv"
crow1=$(format_csv_row "$comp_csv" 2)
crow2=$(format_csv_row "$comp_csv" 3)
echo "| Usage Freq. $crow1" >> "$REPRO"
echo "| Compl.      $crow2" >> "$REPRO"
echo "" >> "$REPRO"

# MRF
echo "**MRF (103 data points)**" >> "$REPRO"
echo "" >> "$REPRO"
echo "| Term        |   OR | Estimate | StdError | t-value | p-value |" >> "$REPRO"
echo "| ----------- | ---: | -------: | -------: | ------: | ------: |" >> "$REPRO"
mrf_csv="results/Table-9-rq2-mrf.csv"
mrow1=$(format_csv_row "$mrf_csv" 2)
echo "| Usage Freq. $mrow1" >> "$REPRO"

# Section 5: Invoke the formatter inside submission tags (required by judge)
echo '<artisan_submit>'
artisan format --expected /workspace/expected.md --repro /workspace/repro.txt
echo '</artisan_submit>'

# Cleanup
docker rm -f rexp_repro >/dev/null 2>&1 || true

