[[artifact]]
title = "PacDroid: A Pointer-Analysis-Centric Framework for Security Vulnerabilities in Android Apps"
conference = "ICSE"
year = 2025
badges = ["Available", "Functional", "Reusable"]
award = ["Best Artifact Award"]
paper_link = "https://zenodo.org/records/14863334/files/paper.pdf"
artifact_link = "https://zenodo.org/records/14749911"

[[artifact]]
title = "ROSA: Finding Backdoors with Fuzzing"
conference = "ICSE"
year = 2025
badges = ["Available", "Functional", "Reusable"]
award = ["Best Artifact Award"]
paper_link = "https://arxiv.org/pdf/2505.08544"
artifact_link = "https://zenodo.org/records/14724251"

# TODO: check ICSE 2024 artifact award winners
# TODO: check ICSE 2023 artifact award winners
# TODO: check ICSE 2022 artifact award winners
# TODO: check ICSE 2021 artifact award winners
# TODO: check ICSE 2020 artifact award winners
# TODO: check ICSE 2019 artifact award winners

# TODO: check FSE 2025 artifact award winners

[[artifact]]
title = "A transferability study of interpolation-based hardware model checking for software verification"
conference = "FSE"
year = 2024
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3660797"
artifact_link = "https://dl.acm.org/do/10.5281/zenodo.11070973/full/"

[[artifact]]
title = "BARO: Robust Root Cause Analysis for Microservices via Multivariate Bayesian Online Change Point Detection"
conference = "FSE"
year = 2024
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/10.1145/3660805"
artifact_link = "https://dl.acm.org/do/10.5281/zenodo.11094092/full/"

# TODO: check FSE 2023 artifact award winners
# TODO: check FSE 2022 artifact award winners
# TODO: check FSE 2021 artifact award winners
# TODO: check FSE 2020 artifact award winners
# TODO: check FSE 2019 artifact award winners
# TODO: check FSE 2018 artifact award winners
# TODO: check FSE 2017 artifact award winners
# TODO: check FSE 2016 artifact award winners
# TODO: check FSE 2015 artifact award winners
# TODO: check FSE 2014 artifact award winners
# TODO: check FSE 2013 artifact award winners
# TODO: check FSE 2012 artifact award winners
# TODO: check FSE 2011 artifact award winners

# TODO: check ASE 2025 artifact award winners
# TODO: check ASE 2024 artifact award winners
# TODO: check ASE 2023 artifact award winners
# TODO: check ASE 2022 artifact award winners
# TODO: check ASE 2021 artifact award winners
# TODO: check ASE 2020 artifact award winners

# TODO: check ISSTA 2025 artifact award winners

[[artifact]]
title = "Unimocg: Modular Call-Graph Algorithms for Consistent Handling of Language Features"
conference = "ISSTA"
year = 2024
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3650212.3652109"
artifact_link = "https://doi.org/10.5281/zenodo.10890011"

[[artifact]]
title = "AGORA: Automated Generation of Test Oracles for REST APIs"
conference = "ISSTA"
year = 2023
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3597926.3598114"
artifact_link = "https://zenodo.org/records/7970822"

[[artifact]]
title = "GPUHarbor: Testing GPU Memory Consistency at Large (Experience Paper)"
conference = "ISSTA"
year = 2023
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3597926.3598095"
artifact_link = "https://doi.org/10.5281/zenodo.7922486"

[[artifact]]
title = "Reducing the Memory Footprint of IFDS-Based Data-Flow Analyses using Fine-Grained Garbage Collection"
conference = "ISSTA"
year = 2023
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3597926.3598041"
artifact_link = "https://doi.org/10.1145/3597926.3598041"

[[artifact]]
title = "That’s a Tough Call: Studying the Challenges of Call Graph Construction for WebAssembly"
conference = "ISSTA"
year = 2023
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3597926.3598104"
artifact_link = "https://doi.org/10.5281/zenodo.7977752"

# TODO: check ISSTA 2022 artifact award winners

[[artifact]]
title = "Automated Patch Backporting in Linux (Experience Paper)"
conference = "ISSTA"
year = 2021
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3460319.3464821"
artifact_link = "https://doi.org/10.5281/zenodo.7977752"

[[artifact]]
title = "Finding data compatibility bugs with JSON subschema checking"
conference = "ISSTA"
year = 2021
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3597926.3598104"
artifact_link = "https://zenodo.org/record/4759197"

[[artifact]]
title = "Data loss detector: automatically revealing data loss bugs in Android apps"
conference = "ISSTA"
year = 2020
badges = ["Available", "Reusable", "Functional"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3395363.3397379"
artifact_link = "https://doi.org/10.5281/zenodo.3897315"

[[artifact]]
title = "Discovering Discrepancies in Numerical Libraries"
conference = "ISSTA"
year = 2020
badges = ["Available", "Reusable", "Functional"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3395363.3397380"
artifact_link = "https://doi.org/10.5281/zenodo.3862978"

[[artifact]]
title = "Feasible and stressful trajectory generation for mobile robots"
conference = "ISSTA"
year = 2020
badges = ["Available", "Reusable", "Functional"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3395363.3397380"
artifact_link = "https://doi.org/10.5281/zenodo.3901626"

# TODO: check ISSTA 2019 artifact award winners

[[artifact]]
title = "Semantic Fuzzing with Zest"
conference = "ISSTA"
year = 2019
badges = ["Available", "Reusable", "Functional"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3293882.3330576"
artifact_link = "https://dl.acm.org/do/10.1145/3339069/full/"

[[artifact]]
title = "Tests from traces: automated unit test extraction for R"
conference = "ISSTA"
year = 2018
badges = ["Available", "Reusable"]
award = ["Distinguished Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/3213846.3213863"
artifact_link = "https://doi.org/10.5281/zenodo.1306437"

# TODO: check ISSTA 2017 artifact award winners

# TODO: check ISSTA 2016 artifact award winners

[[artifact]]
title = "Feedback-controlled random test generation"
conference = "ISSTA"
year = 2015
badges = ["Evaluated"]
award = ["Best Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/2771783.2771805"
artifact_link = "https://www.klazz.net/pub/issta2015/135-update.zip"

[[artifact]]
title = "Covrig: A Framework for the Analysis of Code, Test, and Coverage Evolution in Real Software"
conference = "ISSTA"
year = 2014
badges = ["Evaluated"]
award = ["Best Artifact Award"]
paper_link = "https://dl.acm.org/doi/pdf/10.1145/2610384.2610419"
artifact_link = "https://srg.doc.ic.ac.uk/projects/covrig/"
