[core]
disable_color = true
runtime = "docker"
default_agent = "CodeActAgent"

[llm]
model="openhands/kimi-k2-0711-preview"
api_key="sk-ULKxYTTHqJy7d6j62I5e8w"
#base_url = ""

[sandbox]
timeout=600
volumes = "/var/run/docker.sock:/var/run/docker.sock:rw"

[security]
#confirmation_mode = false
#security_analyzer = ""
