[core]
disable_color = true
runtime = "docker"
default_agent = "CodeActAgent"

[llm]
model="openai/gpt-4o-mini"
api_key="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"

[sandbox]
timeout=600
docker_runtime_kwargs = { privileged = true }
