[core]
disable_color = true
runtime = "docker"
default_agent = "CodeActAgent"

[llm]
model="openai/gpt-4o-mini"
api_key="$OPENAI_API_KEY"
#base_url = ""

[sandbox]
timeout=600
volumes = "/var/run/docker.sock:/var/run/docker.sock:rw"

[security]
#confirmation_mode = false
#security_analyzer = ""
